uint64 timestart

float32 YawRate
float32 PitchRate
float32 RollRate

float32 Temp
float32 pressure

float32 dX
float32 dY
float32 dZ

float32 cgX
float32 cgY
float32 cgZ

float32 YawAngle
float32 Pitch
float32 Roll

float32 accelN 
float32 accelE
float32 accelD

float32 Xaccel
float32 Yaccel
float32 Zaccel

float32 laccelN
float32 laccelE
float32 laccelD

float32 yaw1
float32 pitch1
float32 roll1

int32 AHRS_Status