float32 desired_pos_x1
float32 desired_pos_y1
float32 desired_pos_x2
float32 desired_pos_y2
float32 desired_pos_xc
float32 desired_pos_yc
float32 nominal_velocity
int16 arc_follow_direction
int16 guidance_on
int16 guidance_mode
int16 update_inputs
---
float32 desired_pos_x1
float32 desired_pos_y1
float32 desired_pos_x2
float32 desired_pos_y2
float32 desired_pos_xc
float32 desired_pos_yc
float32 nominal_velocity
int16 arc_follow_direction
int16 guidance_on
int16 guidance_mode
int16 guidance_status
